[package]
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
description = "A modular scrobbler with variety."
homepage = "https://github.com/shymega/scrobble.rs"
license = "GPL-3.0"
name = "scrobble.rs"
readme = "README.md"
repository = "https://github.com/shymega/scrobble.rs.git"
version = "0.1.0"

[lib]
name = "scrobble"
path = "src/lib.rs"

[[bin]]
name = "scrobbled"
path = "src/bin/scrobbled.rs"

[[bin]]
name = "scrobblectl"
path = "src/bin/scrobblectl.rs"

[dependencies]
log = "0.3.8"
mpd = "0.0.12"
time = "0.1.38"
rusqlite = "0.13.0"

[dependencies.clap]
features = ["suggestions", "color", "wrap_help"]
version = "2.29.0"
