[package]
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
description = "A modular scrobbler for a variety of music players."
homepage = "https://github.com/shymega/rscribble"
license = "GPL-3.0"
name = "rscribble"
readme = "README.md"
repository = "https://github.com/shymega/rscribble.git"
version = "0.1.0"

[lib]
name = "rscribble"
path = "src/lib.rs"

[[bin]]
name = "rscr"
path = "src/bin/rscribble.rs"

[dependencies]
log = "0.3.6"
mpd = "0.0.11"
time = "0.1.35"

[dependencies.clippy]
optional = true
version = "0.0.104"

[dependencies.clap]
features = [ "suggestions", "color", "wrap_help"]
version = "2"
