[package]
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
description = "A modular scrobbler for a variety of music players."
homepage = "https://github.com/shymega/rscribble"
license = "GPL-3.0"
name = "rscribble"
readme = "README.md"
repository = "https://github.com/shymega/rscribble.git"
version = "0.1.0"

[lib]
name = "rscribble"
path = "src/lib.rs"

[[bin]]
name = "rscribd"
path = "src/bin/rscribd.rs"

[[bin]]
name = "rscribctl"
path = "src/bin/rscribctl.rs"

[dependencies]
log = "0.3.7"
mpd = "0.0.11"
time = "0.1.36"

[dependencies.clippy]
optional = true
version = "0.0.119"

[dependencies.clap]
features = ["suggestions", "color", "wrap_help"]
version = "2.21.1"
